<?php
/**
 * Smart E-commerce do Brasil Tecnologia LTDA
 *
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category    Esmart
 * @package     Esmart_PayPalBrasil
 * @copyright   Copyright (c) 2013 Smart E-commerce do Brasil Tecnologia LTDA. (http://www.e-smart.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author     	Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

/** @var $this Mage_Paypal_Block_Express_Shortcut */

$shortcutHtmlId = $this->getShortcutHtmlId();

$loader = $this->getLayout()->getBlock('paypalbrasil.express.loader');
$loaderId = $loader->getLoaderId();
?>
<p class="paypal-logo">

<?php if ($this->isOrPositionBefore()): ?>
    <span class="paypal-or"><?php echo $this->__('-OR-');?></span>
<?php endif; ?>
<input type="image" id="<?php echo $shortcutHtmlId ?>"
       src="<?php echo $this->getImageUrl()?>"
       alt="<?php echo Mage::helper('paypal')->__('Checkout with PayPal');?>"
       title="<?php echo Mage::helper('paypal')->__('Checkout with PayPal');?>" />
<?php if ($this->isOrPositionAfter()): ?>
    <span class="paypal-or"><?php echo $this->__('-OR-');?></span>
<?php endif; ?>

<?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
    <?php if ($this->getIsInCatalogProduct()): ?>
        <input type="hidden" id="pp_checkout_url" name="return_url" value="" />
    <?php endif; ?>

    <?php if ($this->getConfirmationUrl()): ?>
    <script type="text/javascript">
    //<![CDATA[

        Event.observe('<?php echo $shortcutHtmlId ?>', 'click', function(event) {
            if (confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->getConfirmationMessage())?>')) {
                var checkboxes = $jPPPlus('.agree input[type="checkbox"]').length;

                if (checkboxes == 0) {
                    EsmartPayPalBrasilProcessedCheckout();
                    return true;
                }

                $jPPPlus(".agreementsAction").trigger('click');
            }
        });

        function EsmartPayPalBrasilProcessedCheckout() {
            var confirmationUrl = '<?php echo $this->getConfirmationUrl() ?>';

            var checkboxes = $jPPPlus('.agree input[type="checkbox"]').length;
            var checkboxesChecked = $jPPPlus('.agree input[type="checkbox"]:checked').length;
            if (checkboxes > checkboxesChecked) {
                alert('<?php echo $this->__('Please agree to all Terms and Conditions before placing the order.')?>');
                return false;
            }

            $jPPPlus('<?php echo $loaderId ?>').show();

            <?php if ($this->getIsInCatalogProduct()): ?>
            $jPPPlus('pp_checkout_url').value = confirmationUrl;
            productAddToCartForm.submit($jPPPlus('#product_addtocart_form'));
            <?php else: ?>
            window.location = confirmationUrl;
            <?php endif; ?>
        }
    //]]>
    </script>
    <?php endif; ?>
<?php endif; ?>
</p>
