<?php
/**
 * Smart E-commerce do Brasil Tecnologia LTDA
 *
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category  Esmart
 * @package   Esmart_PayPalBrasil
 * @copyright Copyright (c) 2015 Smart E-commerce do Brasil Tecnologia LTDA. (http://www.e-smart.com.br)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author    Thiago H Oliveira <thiago.oliveira@e-smart.com.br>
 */
/** @var Mage_Core_Block_Template $this */
?>

<a class="agreementsAction" href="#agreementsBox"
   style="display: none"
   title="<?php echo $this->__('Terms and Conditions')?>">#</a>

<div id="agreementsBox" style="width:500px; display: none;">
    <?php echo $this->getBlockHtml('checkout.onepage.agreements') ?>
    <button id="agreementsContinue" class="button" title="Proceed to Checkout" type="button">
        <span>
            <span><?php echo $this->__('Continue')?></span>
        </span>
    </button>
</div>

<script>

    jQuery(document).ready(function () {
        jQuery(".agreementsAction").fancybox({
            maxWidth    : 800,
            maxHeight   : 600,
            fitToView   : false,
            width       : '60%',
            height      : '60%',
            autoSize    : false,
            closeClick  : false,
            openEffect  : 'none',
            closeEffect : 'none'
        });

        jQuery('#agreementsContinue').click(function(e){
            EsmartPayPalBrasilProcessedCheckout();
        });
    });
</script>