<?php
/**
 * Smart E-commerce do Brasil Tecnologia LTDA
 *
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category    Esmart
 * @package     Esmart_PayPalBrasil
 * @copyright   Copyright (c) 2013 Smart E-commerce do Brasil Tecnologia LTDA. (http://www.e-smart.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author      Thiago H Oliveira <thiago.oliveira@e-smart.com.br>
 */
?>
<?php
/** @var Mage_Sales_Model_Quote_Payment $info */
$info = $this->getInfo();
?>
<p>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
</p>
<?php
$cards = $info->getAdditionalInformation('paypal_plus_cards');
?>

<?php if ($cards): ?>
<p>
    <?php
    foreach ($cards as $card) {
        echo $this->getCardInformation($card);
        echo '<br>';
    }
    ?>
</p>
<?php endif; ?>
