<?php
/**
 * Smart E-commerce do Brasil Tecnologia LTDA
 *
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category    Esmart
 * @package     Esmart_PayPalBrasil
 * @copyright   Copyright (c) 2013 Smart E-commerce do Brasil Tecnologia LTDA. (http://www.e-smart.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author      Thiago H Oliveira <thiago.oliveira@e-smart.com.br>
 */
?>
<?php
/** @var Mage_Sales_Model_Order_Payment $info */
$info = $this->getInfo();
?>
<div class="payflow-settings-notice">
    <p>
        <strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong>
    </p>

    <br>

    <p>
        <strong>Checkout Token : </strong><?php echo $info->getAdditionalInformation('paypal_plus_checkout_token'); ?>
    </p>

    <p>
        <strong>Sale ID :</strong>
        <?php echo $info->getAdditionalInformation('paypal_plus_sale_id'); ?>
    </p>

    <p>
        <strong>Payment ID (state) : </strong>
        <?php echo "{$info->getAdditionalInformation('paypal_plus_payment_id')} ({$info->getAdditionalInformation('paypal_plus_payment_state')})"; ?>
    </p>

    <p>
        <strong>Payer ID :</strong>
        <?php echo $info->getAdditionalInformation('paypal_plus_payer_id'); ?>
    </p>

    <?php
    $cards = $info->getAdditionalInformation('paypal_plus_cards');
    ?>

    <?php if ($cards): ?>
        <p>
            <strong>Dados da Transação :</strong>
        </p>

        <?php foreach ($cards as $card): ?>
            <small>
                <strong>Cartão de crédito</strong> <br>
                <strong>- Parcela(s): </strong><?php echo "{$card['termQty']}x de {$card['termValue']}"; ?> <br>
                <?php if ($card['termQty'] > 1): ?>
                    <strong>- Total: </strong><?php echo $card['total']; ?>
                <?php endif; ?>
            </small>
            <br>
        <?php endforeach; ?>

    <?php endif; ?>
</div>
